현초은 [로또] 제출합니다.
croffle-lover/java-lotto pull request #1
Opened 2023-07-03 09:29 UTC by 2384320

https://swift-badge-161.notion.site/53ad907c1bbe4eb4a8375b144bb3327b?pvs=4
요거는 늘 드렸던 노션 링크에여

2023-07-04 11:13 UTC, bandal-reviewer requested changes
안녕하세요 초은님 로또미션 고생 많으셨습니다!
메서드 분리, 클래스 분리, 패키지 분리 등 여러가지로 분리하느라 고생 많으셨습니다!
왜 이렇게 까지 분리하는지 한번쯤 생각해보면 좋을 것 같습니다!
몇가지 코멘트 남겼으니 질문한 점에대해 댓글 남겨주시고 다시 리뷰요청 주세요! 

참고로 pr은 닫지 않고 그대로 수정하여 커밋 푸시한다음 저한테 알려주시면 됩니다!

2023-07-04 11:13 UTC, croffle-lover commented on src/main/java/lotto/Controller/Controller.java
> +public class Controller {
MVC 아키텍쳐 패턴의 Controller 역할을 하는 클래스인 것 같습니다.
다만 어떤 것의 Controller 인지 확실히 명시해주는게 좋아보입니다.
힌트 : `xxxController`

2023-07-04 11:13 UTC, croffle-lover commented on src/main/java/lotto/Domain/LottoNumbers.java
> +}
`LottoNumbers`는 이름만 보면 LottoNumber 객체를 여러개 가지고 있는 자료구조라는 생각이 듭니다.
하지만 정작 하는일은 랜덤 숫자로 이루어진 배열을 6개 뽑아 반환하는 메서드만 가지고 있습니다.
다른 클래스 명이 어울려 보입니다.

2023-07-04 11:13 UTC, croffle-lover commented on src/main/java/lotto/UI/Output.java
> +    private static final String RESULT_VIEW = "당첨 통계\n---";
에러메시지를 상수화 해주셨네요!
우리가 상수화를 하는 이유는 무엇이었나요? 댓글로 남겨주세요.

2023-07-04 11:13 UTC, croffle-lover commented on src/main/java/lotto/Domain/WinningNumberSet.java
> +public class WinningNumberSet {
Set, List와 같이 자료구조의 이름이 변수명 또는 클래스명에 포함되는 것은 혼란을 야기할 수 있으니 가급적 자제하는 것이 좋습니다. :)
왜 혼란을 야기할 수 있을지 생각해보는 것도 좋을 것 같네요.

2023-07-04 11:13 UTC, croffle-lover commented on src/main/java/lotto/Domain/WinningNumberSet.java
> +    private final Lotto numbersList;
`Lotto` 클래스의 인스턴스의 이름은 `lotto` 처럼 클래스 명을 따라는 것이 인스턴스의 이름만 보고도 어떤 클래스를 인스턴스화 한건지를 유추할 수 있습니다.

2023-07-04 11:13 UTC, croffle-lover commented on src/main/java/lotto/Domain/Winning.java
> +    SIX_WINNING(6, 2_000_000, "6개 일치 (2,000,000,000원) - ");
조금더 도메인적으로 표현해도 좋을 것 같습니다.
6개 맞췄다 이런 느낌보단 1등이라고 표현하는 것이 좋아보입니다.

2023-07-04 11:13 UTC, bandal-reviewer commented on src/main/java/lotto/Domain/Winning.java
> +    SIX_WINNING(6, 2_000_000, "6개 일치 (2,000,000,000원) - ");
또한 "3개 일치 (5,000원) -"과 같은 문자열은 UI의 [관심사](https://ko.wikipedia.org/wiki/%EA%B4%80%EC%8B%AC%EC%82%AC_%EB%B6%84%EB%A6%AC)가 아닐까요?

이 미션은 다음과 같은 요구사항이 있습니다.
> 핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 분리해 구현한다.

2023-07-04 11:13 UTC, bandal-reviewer commented on src/main/java/lotto/Controller/Controller.java
> +    }
1000으로 나누는 행위는 `Controller`에서 할 일일까요? 혹은 다른 곳에서 할 일일까요?

2023-07-04 11:13 UTC, bandal-reviewer commented on src/main/java/lotto/Domain/PurchasePrice.java
> +    private final String price;
price가 String인 이유는 무엇인가요?

2023-07-04 11:32 UTC, 2384320 commented on src/main/java/lotto/UI/Output.java
> +    private static final String RESULT_VIEW = "당첨 통계\n---";
- 유지보수를 쉽게 하기 위해서
- 처음보는 사람이 코드를 읽었을 때 어떤 데이터인지 알도록 하기 위해서
라고 알고 있습니다.

2023-07-04 11:38 UTC, 2384320 commented on src/main/java/lotto/Domain/WinningNumberSet.java
> +public class WinningNumberSet {
혼란을 야기하는 이유(?)
당장 제 코드만 봐도 WinningNumberList 같이 해당 변수가 리스트임을 알리는 명칭이 있는데
이런 작명 규칙에서 WinningNumberSet이 나오면 '이건 당첨 번호 Set이겠구나' 라고 이해하는 게 당연하겠네여..

2023-07-04 11:59 UTC, 2384320 commented on src/main/java/lotto/Domain/PurchasePrice.java
> +    private final String price;
이 부분에 대해서 질문하고 싶었던 것도 있었어요

이번 미션에서 잘못된 형식으로 입력됐을 떼 IllegalArgumentException로 예외 처리를 하라고 하더라고요
이 상태에서 만약에 제가 price를 int로 받는다고 했을 때 숫자가 아닌 문자를 입력하게 되면
입력하는 순간에 바로 FormatException 같은 형식 예외가 나올 것 같더라고요
그래서 차라리 String으로 받은 다음에 String.matches()로 검사 한 후에
나중에 필요하면 그때 int 형식으로 변환해서 내보내도록 하면 어떨까 하면서 만들어진 결과였습니다.

질문하고 싶었던 건 저 위에 제가 고민했던 것처럼 _"FormatException과 같은 예외가 발생하는 것 까지 IllegalArgumentException로 바꿔서 예외 처리를 해야하는지"_입니다.

근데 이렇게 쓰다보니깐 validate(price) 해준 이후에 getPrice() 함수에서 반환 값만 int로 바꾸는 것이 아니라
this.price = Integer.parseInt(price) 이런 식으로 해도 됐을 것 같네요..

2023-07-04 12:01 UTC, 2384320 commented on src/main/java/lotto/Controller/Controller.java
> +    }
도메인에서 해야 돼요..

2023-07-05 02:30 UTC, bandal-reviewer requested changes
피드백받은 부분 수정 고생많으셨습니다!!

추가로 코멘트에 댓글로 질문 답변 남겼습니다! 

아참 그리고 conversation resolve는 제가 잘 고쳤는지 확인하고 누를게요!

조금 더 고쳐봅시다 화이팅!

2023-07-05 02:30 UTC, croffle-lover commented on src/main/java/lotto/Controller/LottoController.java
> +        }
try - catch 형태로 에러처리를 해주신 점 좋습니다. 
하지만 다음과 같이`IllegalArgumentException`로 부터 메시지를 받을 수 있습니다.
```java
try {
    startLotto();
} catch (IllegalArgumentException exception) {
    Output.printExceptionMessage(exception.getMessage);
}
```
그대로 프린트만 해주면 되는거죠!

2023-07-05 02:30 UTC, bandal-reviewer commented on src/main/java/lotto/Controller/LottoController.java
> +    }
`setGameOver`라고 메서드 네임을 지어주셨네요!
나중에 프로젝트 개념으로 들어가시면 아시겠지만, 
get 과 set은 getter setter라는 개념이 있을 정도로 흔히 사용하는 메서드 네임 접두사입니다.
그래서 다른사람이 이 코드를 처음 봤을 땐 우리가 통상적으로 생각하는 개념(get- 값을 가져옴, set- 값을 세팅)이 먼저 떠올라요.
제 생각엔 그런 늬앙스를 느껴지게하는 메서드는 컨트롤러에는 없어야한다 생각합니다. 
수정해주세요!

2023-07-05 02:30 UTC, bandal-reviewer commented on src/main/java/lotto/Domain/BonusNumber.java
> +    }
보너스 넘버 클래스를 만들어주셨네요? `VO(값 객체)` 역할을 하는 것 같습니다. 
올바른 값 객체 만드는 방법을 배우시고 적용시켜 보시는거 어떨까요?

LottoNumber도 있으면 좋지 않을까요? ㅎㅎ

2023-07-05 02:30 UTC, bandal-reviewer commented on src/main/java/lotto/Domain/BonusNumber.java
> +    }
사실 
`throw new IllegalArgumentException("이름이 너무 길어요~")`
이처럼  에러 메시지를 지정할 수 있습니다.
문제는 이 메시지가 사용자한테 보여지지 않는다는거죠 ㅎㅎ

그럼 우리는 어떻게 이렇게 지정해준 메시지를 사용자에게 출력해줄 수 있을까요?
힌트? 는 이미 드렸습니다 사실 ㅎㅎ

2023-07-05 02:30 UTC, bandal-reviewer commented on src/main/java/lotto/Domain/PurchasePrice.java
> +    }
구매하고자 하는 금액에 따라 로또의 장수를 계산해주는 메서드네요.
문제는 이 PurchasePrice를 만약 로또가 아닌 다른경우, 예를들어 영화 티켓을 끊는다고 하면 불필요한 메서드가 포함된 클래스인 `PurchasePrice`를 사용하게 되는거네요?

**정리하자면 과연 금액의 역할을 하는 이 클래스는 로또를 알고 있어야 할까요?**

2023-07-05 02:30 UTC, bandal-reviewer commented on src/main/java/lotto/UI/Output.java
> +    private static final String RESULT_VIEW = "당첨 통계\n---";
맞습니다.
추가로 여러군데에서 쓰인 변수를 한 번에 바꿀 수 있다도 되겠네요!

정리하자면 다음과 같습니다.
1. 여러군데에서 쓰인 변수명을 한번에 바꿀 수 있다. 
    - 에러메시지의 경우 재사용하는 경우가 많지 않습니다. 만약 재사용을 할 에러메시지라면 그 때가서 고민하는 것이 좋습니다.
3. 처음 보는 사람이 코드를 읽었을 때 어떤 데이터인지 알도록 할 수 있다.
    - 에러메시지의 경우 서술형으로 풀어 적혀있기 때문에 다른사람이 보더라도 소설책 읽듯 그냥 읽으면 되기 때문에 뜻이 전달안되는 문제는 없습니다!

이와 같은 이유로 에러메시지는 보통 상수화 하지 않습니다!

2023-07-05 02:31 UTC, bandal-reviewer commented on src/main/java/lotto/Domain/PurchasePrice.java
> +    private final String price;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 좋습니다.

2023-07-08 09:42 UTC, bandal-reviewer requested changes
피드백 반영하시느라 고생 많으셨습니다!!!
조금만 더 화이팅 해보죠!
질문 많이 해주세요~

2023-07-08 09:42 UTC, bandal-reviewer commented on src/main/java/lotto/Domain/LottoNumber.java
> +    private static final int MAXIMUM_NUMBER_RANGE = 45;
기존에 있던 `BonusNumber`가 사라지고 `LottoNumber`로 통일 시켜주셨군요! 
제가 값객체(VO)로 만드는거로 피드백 드렸는데 아쉽지만! 아직은 기능이 모자랍니다.
> 값객체의 특성
Immutability(불변성) - 수정자가(setter) 없다
value equality(값 동등성) - 내부 값 동등성 검사
self validation(자가 유효성 검사) - 생성자에서 validate

`System.out.println(new LottoNumber(1).equals(new LottoNumber(1)));`
이 친구의 출력값은 무엇일까요? 예상대로 안나온다면 그건 무엇 때문일까요?

2023-07-08 09:42 UTC, bandal-reviewer commented on src/main/java/lotto/Domain/LottoNumber.java
> +    private static final int MAXIMUM_NUMBER_RANGE = 45;
로또 넘버는 총 45개입니다. 
바꿔서 말하면 45개 외에 생성될리 없는 친구에요.
흠~ 그럼 어떻게 하는게 좋을까요?
어떤 저장공간을 하나 만들어서
로또 넘버 1이 필요하다면 1이 있는지 확인하고 없다면 생성해서 넣어두고,
또다시 1이 필요하면? 이미 저장해둔 1을 가져와 반환해주면 되겠죠? 
힌트 : [정적 팩토리 메서드](https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/)

2023-07-08 09:42 UTC, bandal-reviewer commented on src/main/java/lotto/Application.java
>  public class Application {
어허~ `Ctrl + Alt + L`  잊지 말아주세요~

>팁: lotto 패키지 한번 클릭하고 단축키 사용하면 해당 패키지 안에 있는 모든 파일들이 정렬됩니다. ㅎ

2023-07-08 09:42 UTC, bandal-reviewer commented on src/main/java/lotto/Domain/Lotto.java
> +    }
우린 `LottoNumber`를 만들었습니다.
그러면 `Lotto`는 `LottoNumber` 여러개를 컬렉션을 통해 가지고 있어야하지 않을까요?

2023-07-09 10:23 UTC, 2384320 commented on src/main/java/lotto/Domain/LottoNumber.java
> +    private static final int MAXIMUM_NUMBER_RANGE = 45;
false 입니다
왜냐하면 new LottoNumber(1)는 고유의 객체를 생성하는 것이기 때문에 아무리 같은 값 1로 생성한다고 하더라도 생성된 객체 자체는 다르기 때문입니다.

2023-07-09 10:34 UTC, 2384320 commented on src/main/java/lotto/Domain/LottoNumber.java
> +    private static final int MAXIMUM_NUMBER_RANGE = 45;
setter -> final로 해결하기
value equality -> Object에서 equals와 hashCode 오버라이딩
self validation -> validateRange로 해결
겠죠..?

2023-07-14 12:08 UTC, bandal-reviewer approved these changes
로또 미션 고생 많으셨습니다!
원하는 개발자가 되기위한 큰 한 걸음이었으면 좋겠습니다!

몇가지 코멘트 남겼으니 확인해주세요~

2023-07-14 12:08 UTC, bandal-reviewer commented on src/main/java/lotto/Domain/LottoNumberVO.java
> +    private static final int MINIMUM_NUMBER_RANGE = 1;
VO 또한 줄인말이죠??
그치만 우린 이름이 길어져도 줄이지 않기로 하였습니다!
`LottoNumberValueObject` --> 이건 또 너무 길죠? ㅎㅎ
`LottoNumber`로 해도 충분히 의미 전달이 될것 같아요 ㅎㅎ

2023-07-14 12:08 UTC, bandal-reviewer commented on src/main/java/lotto/Domain/LottoNumberVO.java
> +    }
우린 정적 팩토리 메서드를 사용하여 생성자의 역할을 대신하는 친구를 만들었습니다.
그치만 현재처럼 public으로 생성자가 공개되어있다면, 원치않는 중복되는 인스턴스가 생기는 것을 막을 수가 없습니다.
실제로 `LottoNumberVO(1)`를 한다면 인스턴스가 생기는 것을 볼 수 있을 겁니다.
접근제어자를 바꾸어 외부에 노출되지 않고 팩토리 메서드만 생성자를 사용할 수 있도록 해볼까요?ㅎㅎ

2023-07-14 12:09 UTC, merged